<?php
/**
* AkoLegal - A Mambo Disclaimer Component
* @version 2.0
* @package AkoLegal
* @copyright (C) 2003, 2004 by Arthur Konze - All rights reserved!
* @license http://www.konze.de/content/view/8/26/ Copyrighted Commercial Software
**/

# Imprint
define('_ALIMPRINT','Imprint');
define('_ALCOMPANY_INFO','Company information');
define('_ALPHO','Phone:');
define('_ALFAX','Fax:');
define('_ALMOB','Mobile:');
define('_ALURL','Website:');
define('_ALEMA','Email:');
define('_ALBANK_INFO','Bank information');
define('_ALBANACC','Account number:');
define('_ALBANNAM','Bank name:');
define('_ALBANCOD','Bank code:');
define('_ALBANIBA','IBAN:');
define('_ALBANBIC','SWIFT-BIC:');
define('_ALLEGAL_NOTES','Legal notes');
define('_ALCOMNUM','Company number:');
define('_ALTAXNUM','Tax number:');
define('_ALCONNAM','Content responsible:');
define('_ALTECNAM','Technical responsible:');
define('_ALFURTHER_INFO','Further informations');

# Terms of use
define('_TOUTOPTEXT','Terms of Use for '.$mosConfig_sitename);
define('_TOUTITLE1','1. Acceptance of Terms of Use and Amendments.');
define('_TOUTITLE2','2. Our Service.');
define('_TOUTITLE3','3. Your Responsibilities and Registration Obligations.');
define('_TOUTITLE4','4. Privacy Policy.');
define('_TOUTITLE5','5. Registration and Password.');
define('_TOUTITLE6','6. Your Conduct.');
define('_TOUTITLE7','7. Submission of Content on this Web Site.');
define('_TOUTITLE8','8. Third Party Services.');
define('_TOUTITLE9','9. Indemnification.');
define('_TOUTITLE10','10. Disclaimer of warranties.');
define('_TOUTITLE11','11. Limitation of liability.');
define('_TOUTITLE12','12. Reservation of Rights.');
define('_TOUTITLE13','13. Notification of Copyright Infringement.');
define('_TOUTITLE14','14. Applicable Law.');
define('_TOUTITLE15','15. Miscellaneous Information.');
define('_TOUTEXT1','Each time you use or cause access to this web site, you agree to be bound by these <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a>, and as amended from time to time with or without notice to you. In addition, if you are using a particular service on or through this web site, you will be subject to any rules or guidelines applicable to those services and they shall be incorporated by reference into these <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a>. Please see our <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=privacy">Privacy Policy</a>, which is incorporated into these <a  href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a> by reference.');
define('_TOUTEXT2','Our web site and services provided to you on and through our web site on an &quot;AS IS&quot; basis.You agree that the owners of this web site exclusively reserve the right and may, at any time and without notice and any liability to you,   modify or discontinue this web site and its services or delete the data you   provide, whether temporarily or permanently. We shall have no responsibilty   or liability for the timeliness, deletion, failure to store, inaccuracy, or   improper delivery of any data or information.');
define('_TOUTEXT3','In order to use this web site, you must <a href=index.php?option=com_registration&task=register>register</a> on our site, agree to provide truthful information when requested, and be at   least the age of thirteen (13) or older. When registering, you explicitly agree   to our <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a> and as   may be modified by us from time to time and available here.');
define('_TOUTEXT4','Registration data and other personally identifiable information that we may collect is subject to the terms of our <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=privacy">Privacy Policy</a>.');
define('_TOUTEXT5','You are responsible to maintain the confidentiality of your password and shall   be responsible for all uses via your registration and/or login, whether authorized   or unauthorized by you. You agree to immediately notify us of any unauthorized   use or your registration, user account or password.');
define('_TOUTEXT6','You agree that all information or data of any kind, whether text, software,   code, music or sound, photographs or graphics, video or other materials (&quot;Content&quot;),   publicly or privately provided, shall be the sole responsibility of the person   providing the Content or the person whose user account is used. You agree that   our web site may expose you to Content that may be objectionable or offensive.   We shall not be responsible to you in any way for the Content that appears on   this web site nor for any error or omission.');
define('_TOUTEXT6MORE','You explicitly agree, in using this web site or any service provided, that you shall not:<br />   (a) provide any Content or perform any conduct that may be unlawful, illegal,   threatening, harmful, abusive, harassing, stalking, tortious, defamatory, libelous,   vulgar, obscene, offensive, objectionable, pornographic, designed to or does   interfere or interrupt this web site or any service provided, infected with   a virus or other destructive or deleterious programming routine, give rise to   civil or criminal liability, or which may violate an applicable local, national   or international law;<br />   (b) impersonate or misrepresent your association with any person or entity,   or forge or otherwise seek to conceal or misrepresent the origin of any Content   provided by you;<br />   (c) collect or harvest any data about other users;<br />   (d) provide or use this web site and any Content or service in any commercial   manner or in any manner that would involve junk mail, spam, chain letters, pyramid   schemes, or any other form of unauthorized advertising without our prior written   consent; <br />   (e) provide any Content that may give rise to our civil or criminal liability   or which may consititue or be considered a violation of any local, national   or international law, including but not limited to laws relating to copyright,   trademark, patent, or trade secrets.<br />');
define('_TOUTEXT7','By providing any Content to our web site:<br /> (a) you agree to grant to us a worldwide, royalty-free, perpetual, non-exclusive   right and license (including any moral rights or other necessary rights) to   use, display, reproduce, modify, adapt, publish, distribute, perform, promote,   archive, translate, and to create derivative works and compilations, in whole   or in part. Such license will apply with respect to any form, media, technology   known or later developed;<br />   (b) you warrant and represent that you have all legal, moral, and other rights   that may be necessary to grant us with the license set forth in this Section   7;<br />   (c) you acknowledge and agree that we shall have the right (but not obligation),   in our sole discretion, to refuse to publish or to remove or block access to   any Content you provide at any time and for any reason, with or without notice.<br />');
define('_TOUTEXT8','Goods and services of third parties may be advertised and/or made available on or through this web site. Representations made regarding products and services   provided by third parties are governed by the policies and representations made   by these third parties. We shall not be liable for or responsible in any manner   for any of your dealings or interaction with third parties.');
define('_TOUTEXT9','You agree to indemnify and hold us harmless, our subsidiaries, affiliates, related   parties, officers, directors, employees, agents, independent contractors, advertisers,   partners, and co-branders from any claim or demand, including reasonable attorney\'s   fees, that may be made by any third party, that is due to or arising out of   your conduct or connection with this web site or service, your provision of   Content, your violation of this <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms   of Use</a> or any other violation of the rights of another person or party.');
define('_TOUTEXT10','Your understand and agree that your use of this web site and any services or content provided (the &quot;service&quot;) is made available and provided to you at your own risk. It is provided to you &quot;as is&quot; and we expressly disclaim all warranties of any kind, implied or express, including but not limited to the warrantires of merchantability, fitness for a particular purpose, and non-infringement.');
define('_TOUTEXT10MORE','WE MAKE NO WARRANTY, IMPLIED OR EXPRESS, THAT ANY PART OF THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, VIRUS-FREE, TIMELY, SECURE, ACCURATE, RELIABLE,   OF ANY QUALITY, NOR THAT ANY CONTENT IS SAFE IN ANY MANNER FOR DOWNLOAD. YOU   UNDERSTAND AND AGREE THAT NEITHER US NOR ANY PARTICIPANT IN THE SERVICE PROVIDES   PROFESSIONAL ADVICE OF ANY KIND AND THAT USE OF SUCH ADVICE OR ANY OTHER INFORMATION   IS SOLELY AT YOUR OWN RISK AND WITHOUT OUR LIABILITY OF ANY KIND.');
define('_TOUTEXT10MORE1','Some jurisdictions may not allow disclaimers of implied warranties and the   above disclaimer may not apply to you only as it relates to implied warranties.');
define('_TOUTEXT11','YOU EXPRESSLY UNDERSTAND AND AGREE THAT WE SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INDICENTAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING   BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSS (EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM OR ARISING OUT OF (I) THE USE OF OR THE INABILITY TO USE THE   SERVICE, (II) THE COST TO OBTAIN SUBSTITUTE GOODS AND/OR SERVICES RESULTING   FROM ANY TRANSACTION ENTERED INTO ON THROUGH THE SERVICE, (III) UNAUTHORIZED   ACCESS TO OR ALTERATION OF YOUR DATA TRANSMISSIONS, (IV) STATEMENTS OR CONDUCT   OF ANY THIRD PARTY ON THE SERVICE, OR (V) ANY OTHER MATTER RELATING TO THE SERVICE.');
define('_TOUTEXT11MORE','In some jurisdictions, it is not permitted to limit liability and therefore such limitations may not apply to you.<br />');
define('_TOUTEXT12','  We reserve all of our rights, including but not limited to any and all copyrights, trademarks, patents, trade secrets, and any other proprietary right that we   may have in our web site, its content, and the goods and services that may be   provided. The use of our rights and property requires our prior written consent. We are not providing you with any implied or express licenses or rights by making   services available to you and you will have no rights to make any commercial   uses of our web site or service without our prior written consent.');
define('_TOUTEXT13','If you believe that your property has been used in any way that would be considered copyright infringement or a violation of your intellectual property rights, our copyright agent may be contacted at the following address:<br /><br /><a href=index.php?option=com_akolegal&Itemid='.$Itemid.'>'._ALIMPRINT.'</a>');
define('_TOUTEXT14','You agree that this <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a>   and any dispute arising out of your use of this web site or our products or   services shall be governed by and construed in accordance with local laws where the headquarters of the owner of this web site is located, without regard to its conflict of law provisions. By registering or using this web site and service you consent and submit to the exclusive jurisdiction and venue of the county or city where the headquarters of the owner of this web site is located.');
define('_TOUTEXT15','(i) In the event that this <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms   of Use</a> conflicts with any law under which any provision may be held invalid   by a court with jurisdiction over the parties, such provision will be interpreted   to reflect the original intentions of the parties in accordance with applicable   law, and the remainder of this <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms   of Use</a> will remain valid and intact; (ii) The failure of either party to assert any right under this <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a> shall not be considered a waiver of any that party\'s right and that   right will remain in full force and effect; (iii) You agree that without regard   to any statue or contrary law that any claim or cause arising out of this web   site or its services must be filed within one (1) year after such claim or cause   arose or the claim shall be forever barred; (iv) We may assign our rights and   obligations under this <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a> and we shall be relieved of any further obligation.');

# Terms of use
define('_PPTOPTEXT','Privacy Policy for '.$mosConfig_sitename);
define('_PPTITLEINTRO','Introduction.');
define('_PPTITLE1','1. Collection of Data.');
define('_PPTITLE2','2. Use of Data.');
define('_PPTITLE3','3. Cookies.');
define('_PPTITLE4','4. Children.');
define('_PPTITLE5','5. Editing or Deleting Your Account Information.');
define('_PPTITLE6','6. Changes to this Privacy Policy.');
define('_PPTITLE7','7. No guarantees.');
define('_PPTITLE8','8. Contact Information.');
define('_PPTEXTINTRO','We take your right to privacy seriously and want you to feel comfortable using our web site. This Privacy Policy deals with personally identifiable information (referred to as &quot;Data&quot; below) that may be collected by us on our site. This Policy does not apply to other entities that we do not own or control or persons that are not our employees, agents or within our control. Please take time to read our <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a>.');
define('_PPTEXT1','Our registration process requires only a valid e-mail address and a unique user ID and password. Providing us with other information is at your option. Please take note that your user name, e-mail address, or other submissions that you make on this site may contain your real name or other personally identifiable information and, as a result, may appear on this site. Like many web sites, we may also automatically receive general information that is contained in our server log files such as your IP address and cookie information. Information about how advertising may be served on this site (if at all) is set forth below.');
define('_PPTEXT2','We may use Data to customize and improve your user experience on this site. We will make efforts so that your Data will not be provided to third parties unless (i) provided for otherwise in this Privacy Policy; (ii) we obtain your consent, such as when you choose to opt-in or opt-out to the sharing of Data; (iii) a service provided on our site requires the interaction with or is provided by a third party, by way of example an Application Service Provider; (iv) pursuant to legal process or law enforcement; (v) we find that your use of this site violates our this Policy, Terms of Service, other usage guidelines or as deemed reasonably necessary by us to protect our legal rights and/or property; (vi) or (vi) this site is purchased by a third party whereby that third party will be able to use the Data in the same manner as we can as set forth in this Policy. In the event you choose to use links that appear on our site to visit other web sites, you are advised to read the privacy policies that appear on those sites.');
define('_PPTEXT3','Like many web sites, we set and use cookies to enhance your user experience, such as retaining your personal settings. Advertisements may appear on our web site and, if so, may set and access cookies on your computer and is subject to the privacy policy of those parties providing the advertisement. However, the companies serving the advertising do not have access to our cookies. These companies usually use non-personally identifiable or anonymous codes to obtain information about your visits to our site.');
define('_PPTEXT4','We do not allow persons who are ages thirteen or younger to become members of this   site. For more information, please contact <a href=index.php?option=com_akolegal&Itemid='.$Itemid.'>our webmaster</a>.');
define('_PPTEXT5','We provide you with the ability to edit the information in your user account information that you provided to us in registration by using <a href="index.php?option=com_user&task=UserDetails">your personal page configuration area</a>. You may request deletion of your user account by contacting <a href=index.php?option=com_akolegal&Itemid='.$Itemid.'>our webmaster</a>. Content or other data that you may have provided to us and that is not contained within your user account, such as posts that may appear within our forums, may continue to remain on our site at our discretion even though your user account is deleted. Please see our <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Terms of Use</a> for more information.');
define('_PPTEXT6','We may make changes to this Policy from time to time. We will notify you of substantial changes to this Policy either by posting a prominent announcement on our site and/or by sending a message to the e-mail address you have provided to us that is contained within your user settings.');
define('_PPTEXT7','While this Privacy Policy states our standards for maintenance of Data and we will make efforts to meet them, we are not in a position to guarantee these standards. There may be factors beyond our control that may result in disclosure of data. As a consequence, we disclaim any warranties or representations relating to maintenance or nondisclosure of Data.');
define('_PPTEXT8','If you have any questions about this Policy or our web site, please feel free to contact <a href=index.php?option=com_akolegal&Itemid='.$Itemid.'>our webmaster</a>.');
?>