<?php
/**
* AkoLegal - A Mambo Disclaimer Component
* @version 2.0
* @package AkoLegal
* @copyright (C) 2003, 2004 by Arthur Konze - All rights reserved!
* @license http://www.konze.de/content/view/8/26/ Copyrighted Commercial Software
**/

# Imprint
define('_ALIMPRINT','Ufficio Legale');
define('_ALCOMPANY_INFO','Dati generali');
define('_ALPHO','Telefono:');
define('_ALFAX','Fax:');
define('_ALMOB','Cellulare:');
define('_ALURL','Sito Web:');
define('_ALEMA','Email:');
define('_ALBANK_INFO','Informazioni bancarie');
define('_ALBANACC','Numero Conto:');
define('_ALBANNAM','Nome Banca:');
define('_ALBANCOD','Codice Banca (ABI):');
define('_ALBANIBA','IBAN (CAB):');
define('_ALBANBIC','SWIFT-BIC (Coordinate internazionali):');
define('_ALLEGAL_NOTES','Note Legali');
define('_ALCOMNUM','Numero Compagnia:');
define('_ALTAXNUM','Tax Number:');
define('_ALCONNAM','Responsabile Contenuto:');
define('_ALTECNAM','Responsabile Tecnico:');
define('_ALFURTHER_INFO','Ulteriori informazioni');

# Terms of use
define('_TOUTOPTEXT','Condizioni d\'uso del sito '.$mosConfig_sitename);
define('_TOUTITLE1','1. Accettazione delle condizioni d\'uso ed emendamenti.');
define('_TOUTITLE2','2. Il nostro servizio.');
define('_TOUTITLE3','3. Le Sue responsabilità e gli obblighi di chi si registra.');
define('_TOUTITLE4','4. Privacy.');
define('_TOUTITLE5','5. Registrazione e Password.');
define('_TOUTITLE6','6. La Sua condotta.');
define('_TOUTITLE7','7. Presentazione dei contenuti del sito.');
define('_TOUTITLE8','8. Servizi di terzi.');
define('_TOUTITLE9','9. Indennizzo.');
define('_TOUTITLE10','10. Garanzie.');
define('_TOUTITLE11','11. Limitazione della responsabilità.');
define('_TOUTITLE12','12. Diritti di proprietà intellettuale.');
define('_TOUTITLE13','13. Notifica dell\'infrazione del Copyright.');
define('_TOUTITLE14','14. Legge applicabile.');
define('_TOUTITLE15','15. Informazioni varie.');
define('_TOUTEXT1','Ogni qual volta Lei accede o usa questo sito dovrà accettare le seguenti <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Condizioni d\'uso</a>, che potrebbero cambiare di volta in volta senza preavviso. Inoltre, se Lei sta utilizzando un particolare servizio di questo sito o attraverso questo sito, Lei sarà soggetto alle regole applicate allo stesso e che fanno riferimento alle seguenti <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Condizioni d\'uso</a>. Per favore consultare le <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=privacy">Regole sulla Privacy</a>, che sono all\'interno del documento sulle <a  href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Condizioni d\'uso</a>.');
define('_TOUTEXT2','Il sito ed i servizi forniti attraverso questo sito rispettano le regole sul copyright. Il proprietario di questo sito ne detiene tutti i diritti e può, in qualsiasi momento e senza alcuna responsabilità verso di Lei, modificare o interrompere i servizi provvisti da questo sito o cancellare i dati in esso contenuti, sia temporaneamente che permanentemente. Non abbiamo alcuna responsabilità sulla cancellazione, sulle imprecisioni, sugli errori di inserimento o sull\'uso improprio dei dati e delle informazioni contenute nel sito.');
define('_TOUTEXT3','<a href=index.php?option=com_registration&task=register>Registrandosi</a> a questo sito Lei dichiara di essere d\'accordo con le regole, fornire informazioni veritiere sul suo conto quando richieste, di avere almeno 14 anni e di possedere la capacità giuridica di sottoscrivere un valido contratto. Una volta registrato Lei dichiara esplicitamente di essere d\'accordo con le nostre <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Condizioni d\'uso</a> che possono essere modificate in ogni momento senza preavviso e sono disponibili in queste pagine.');
define('_TOUTEXT4','I dati e le informazioni personali che vengono da noi raccolte all\'atto della registrazione sono soggette alle <a href = "index.php?option=com_akolegal&Itemid = '. $Itemid.' & func=privacy">Regole sulla Privacy</a>.');
define('_TOUTEXT5','ConserVi la Sua username e password in luogo sicuro e protetto. Lei sarà responsabile per ogni uso improprio della Sua registrazione, che sia stata autorizzata o meno da Lei. In caso di smarrimento o furto della Sua username e password Le chiediamo di segnalarcelo immediatamente.');
define('_TOUTEXT6','Lei è a conoscenza che il contenuto del sito, compreso ma non limitato a dati, testi, software, musica, suoni, fotografie, video, grafiche o altro materiale contenuto in qualsiasi forma non limitato solo alla pubblicità o informazioni a fine commerciale, a voi presentati tramite il sito, da noi, o dai nostri pubblicitari, è protetto da copyright, da marchi registrati, marchio di servizio, segreto di mercato, patenti, diritti di database, diritti morali, diritti di pubblicità, diritti di privatezza e altri diritti di proprietà e di legge, tutti appartenenti alla nostra azienda  o a terzi che con essa si identificano. Il nome della nostra azienda o i marchi registrati e i logo usati e mostrati in questo sito non possono venire utilizzati in alcun modo, nè in advertising nè in pubblicità, senza precedente autorizzazione scritta alla nostra azienda . Pertanto chi conoscendo tutte queste informazioni, entra ugualmente nel sito, non potrà rivolgersi a noi per eventuali danni subiti ai sensi dell\'art.1229 c.c., art.2598 c.1, art.1 Legge Marchi, ed eventuali altre leggi vigenti.');
define('_TOUTEXT6MORE','Lei accetta esplicitamente, nel usare questo sito o il servizio in esso fornito, di non:<br/> (a) avere un comportamento che può essere considerato illegale, di minacciare, di essere nocivo, di abusare, di opprimere, di diffamare, di ledere la libertà, di volgarità, di oscenità, di pornografia, interferire o interrompere questo sito o qualunque servizio fornito, infettare con un virus o dell\'altra procedura di programmazione distruttiva o deleteria, provocare responsabilità civile o criminale, o violare una legge; locale, nazionale o internazionale (b)di impersonare o travisare la nostra azienda verso persone o aziende (c) raccogliere qualunque dato circa altri utenti del sito; (d) Non deve interferire con l\'uso che altri utenti fanno del sito nè con i servizi offerti o facendo dei sondaggi , nè con catene di S. Antonio, o "junk mail", "spam" altri mezzi di diffusione di mail indesiderate qualunque altra forma di pubblicità non autorizzata senza il nostro consenso scritto; (e) fornire contenuti che possono portare ad una azione legale nei nostri confronti sia essa civile o che penale, che possono essere considerate una violazione di qualsiasi diritto locale, nazionale o internazionale, includente ma limitate alle leggi per quanto riguarda il copyright, il marchio, il brevetto, o il commercio secreto.<br/>');
define('_TOUTEXT7','Fornendo materiale al nostro sito:<br/> (a) voi accettate la concessione a noi, royalty-free perpetua, la non-esclusività e l\'autorizzazione (di qualsiasi diritto compresi morale o altri diritti necessari) ad usare, visualizzare, riprodurre, modificare, adattare, pubblicare, distribuire, effettuare, promuovere, archiviare, tradurre e generare prodotti derivati, in tutto o in parte.  Tale autorizzazione si applicherà riguardo a tutta la forma, mezzi, sviluppo;<br conosciuto o successivo di tecnologia/> (b) garantite e certificate che avete tutti i diritti legali, morali ed altri diritti che possono essere necessari ad assegnarli con l\'autorizzazione disposta in questa sezione 7;<br/> (c) Voi riconoscete e che abbiamo il diritto (non obbligatorio), nella nostra sola discrezione, di rifiutare di pubblicare o di rimuovere l\'accesso completamente, in qualunque momento, per qualsiasi motivo, con o senza notifica.<br />');
define('_TOUTEXT8','La nostra azienda non ha alcuna responsabilità, diretta o indiretta, per quanto riguarda i siti ai quali è possibile accedere tramite i collegamenti posti all\'interno del seguente sito (forniti come semplice servizio agli utenti della rete); per eventuali danni subiti dall\'utente in relazione al contenuto dei siti o in relazione ad acquisti di beni o servizi effettuati tramite questi siti; la nostra azienda declina al tempo stesso ogni responsabilità riguardante il contenuto e la legalità del materiale presente sui siti linkati dalla  nostra azienda e non è in alcun caso da ritenersi responsabile dell\'eventuale violazione di diritti d\'autore da parte dei siti linkati.
Il fatto che la nostra azienda fornisca questi collegamenti non implica necessariamente l\'approvazione dei siti stessi, sulla cui qualità, contenuti e grafica la nostra azienda declina ogni responsabilità.
');
define('_TOUTEXT9',' Riconoscete che, i suoi affiliati, sussidiari, compagnie consociate, agenti, impiegati, dirigenti e direttori, non saranno responsabili in alcun caso nei suoi confronti o nei confronti di una terza parte per eventuali danni di qualsiasi specie e natura che derivino, direttamente o indirettamente, dalla perdita di informazioni, o profitti, indipendentemente dal fatto che sia stata informata o meno, derivanti o connessi con l\'uso o con le prestazioni del sito; o per non essere stata in grado di offrire i servizi che ha ordinato da o da i suoi affiliati, inclusi senza limitazioni i danni derivanti da errori, omissioni, virus, ritardi, o interruzioni del servizio. In nessun caso sarà responsabile per i danni e le conseguenze derivanti da o relative al suo non appropriato o non autorizzato uso del sito o del suo contenuto. ');
define('_TOUTEXT10',' L\'utente riconosce che non abbiamo il controllo sulle informazioni, i prodotti e servizi offerti da terzi attraverso il sito. Salvo accordi scritti diversi, l\'azienda e le sue consociate, non si assumono alcuna responsabilita\', ne\' concedono alcuna garanzia o assicurazione in merito alla precisione, all\'attualita\', alla completezza, all\'affidabilita\' o all\'utilita\' di qualsiasi consulenza, opinione, dichiarazione, o altro, ne\' in merito a contenuti, prodotti o servizi distribuiti o resi disponibili a cura di terzi, compresi, tra l\'altro, eventuali contenuti relativi agli sponsor tramite il sito. L\'azienda non fornisce alcuna garanzia sulla conformita\' del sito o dei suoi contenuti ai requisiti degli utenti, ne\' in merito al fatto che il medesimo o i suoi contenuti non siano soggetti a interruzioni, siano tempestivi, sicuri ed esenti da errori, ne\' circa il fatto che eventuali difetti saranno eliminati. L\'azienda inoltre non fornisce alcuna garanzia sui risultati eventualmente ottenuti dall\'uso del sito, sui contenuti o sulla precisione, completezza o affidabilita\' di qualsiasi informazione ottenuta mediante l\'uso del sito');
define('_TOUTEXT10MORE','In alcune giurisdizioni non è ammesso limitare le responsabilità, quindi potrebbe essere che alcune limitazioni non siano adattabili al Suo caso.');
define('_TOUTEXT10MORE1',' ');
define('_TOUTEXT11','Il materiale contenuto nel sito è fornito "nello stato in cui è" e senza alcuna garanzia implicita o esplicita. Nei più ampi termini di legge. Si declina ogni responsabilità esplicita o implicita, incluso, ma non limitato, la continuità del servizio, la presenza di errori, la correzione degli errori, la responsabilità del server ospitante il sito sull\'eventuale presenza di virus o altri componenti informatici nocivi e dannosi. La nostra azienda non è responsabile dell\'uso delle informazioni contenute, della loro correttezza e affidabilità. In nessun caso, inclusa la negligenza, l\'azienda sarà responsabile di ogni diretto o indiretto danno che possa risultare dall\'uso, o dalla incapacità di usare, i materiali presenti nel sito.');
define('_TOUTEXT11MORE',' ');
define('_TOUTEXT12','Ci riserviamo tutti i nostri diritti, includendo ma non limitando i copyright, marchi, brevetti, segreti commerciali ed  qualunque altra proprietà  riservata che possiamo avere nel nostro sito, relativamente alle merci, ai servizi che possono essere forniti.  L\'uso di diritti e proprietà richiede il nostro consenso scritto a priori.  Non stiamo fornendo in alcun modo implicitamente o e non esprimiamo nessuna autorizzazioni o diritto a mettere a disposizione i servizi, voi non avete diritto di fare alcun uso commerciale del nostro sito o servizio senza alcun nostro consenso scritto a priori.');
define('_TOUTEXT13','Se pensate che la vostra proprietà intellettuale sia stata usata e che la considerate un infrazione di copyright o una violazione dei vostri diritti di copyright, il vostro agente di copyright può mettersi in contatto con noi al seguente indirizzo: <a href=index.php?option=com_akolegal&Itemid='.$Itemid.'>'._ALIMPRINT.'</a>');
define('_TOUTEXT14','Siete concordi che queste <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Condizioni d\'uso</a> e ogni eventuale disputa relativa all\'uso di questo sito o ai servizi e prodotti offerta saranno regolamentati e in conformità con le leggi locali ove risiede la sede del proprietario del sito stesso.');
define('_TOUTEXT15','Nell\'ipotesi in cui uno qualunque degli articoli o dei paragrafi delle presenti<a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms"> condizioni generali</a > del servizio sia considerato illegittimo da una disposizione di legge o di regolamento presente o futura o da una decisione definitiva dell\'autorità giudiziaria, tale articolo o paragrafo sarà considerato come non apposto, mentre tutte le altre disposizioni delle presenti condizioni generali del servizio conserveranno forze e valore vincolante tra le parti. 
Per accettare le presenti condizioni generali di servizio l\'Utente dichiara ai sensi e per gli effetti dell\'art. 1341, 2° comma, cod. civ., di aver letto con attenzione e di approvare specificamente le pattuizioni contenute negli articoli precedenti riguardanti:
Art. 1.c - Facoltà di recedere dal contratto; Art. 4.A - Limitazioni di responsabilità; Art. 3.A - Restrizione alla libertà contrattuale nei confronti dei terzi; Art. 8 - Legge applicabile e Foro competente. <br /> Queste Condizioni ed il Servizio sono soggetti all\'applicazione del D. lgs n. 185 del 22 maggio 1999. L\'Utente consente espressamente all\'impiego della posta elettronica quale mezzo di comunicazione a distanza. L\'Utente accetta che ai sensi dell\'articolo 4 del suddetto D. lgs la conferma scritta delle informazioni contenute in queste Condizioni sia effettuata per e-mail e si obbliga a scaricarle, stamparle e conservarle');

# Terms of use
define('_PPTOPTEXT','Regole sulla Privacy di '.$mosConfig_sitename);
define('_PPTITLEINTRO','Introduzione.');
define('_PPTITLE1','1. Salvataggio dei dati.');
define('_PPTITLE2','2. Uso dei dati.');
define('_PPTITLE3','3. Cookies.');
define('_PPTITLE4','4. Bambini.');
define('_PPTITLE5','5. Modifica o cancellazione del suo account.');
define('_PPTITLE6','6. Modifiche alle regole sulla Privacy.');
define('_PPTITLE7','7. Nessuna Garanzia.');
define('_PPTITLE8','8. Contatti.');
define('_PPTEXTINTRO',' Molta attenzione è posta per tutelare la riservatezza e la privacy dei visitatori del sito internet. Ciò nonostante, si informa che possono essere automaticamente acquisite, in specifiche parti del sito, informazioni sulle modalità di connessione dei visitatori al fine di fornire la migliore prestazione nella visualizzazione del sito. Esse includono principalmente informazione sul tipo di browser utilizzato, il tipo di sistema operativo e il nome dell\'internet service provider del visitatore. Inoltre sono previste informazioni, esclusivamente in forma aggregata e non identificabili individualmente, sul numero di visitatori e statistiche connesse. Gli indirizzi e-mail e altri dati personali saranno raccolti solo ed esclusivamente se intenzionalmente indicati dal visitatore stesso e in tal caso nessun uso ne verrà fatto al di fuori di quello specifico per il quale sono stati indicati. Questa Politica non viene applica ad altre società che noi non possediamo o controlliamo o persone che non siano i nostri impiegati, agenti o sotto il nostro diretto controllo. Per favore legga con molta attenzione i nostri<a   href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms"> Condizioni d\'uso</a>.');
define('_PPTEXT1','Il nostro processo di registrazione richiede solamente un indirizzo di e-mail valido ed un user ID e una password. Offrirci altre informazioni è a Sua discrezione. Per favore prenda nota del Suo nome di utente, indirizzo di e-mail, o le altre informazioni che Lei fornisce a questo sito. Queste informazioni possono contenere il Suo vero nome o\e altre notizie che possono portarla ad identificarla e, di conseguenza, possono apparire su questo sito. Come i molti sito, noi possiamo ricevere anche informazioni automaticamente generate ove sono contenuti nei nostri archivi di sistema del servizio il Suo indirizzo IP ed informazioni dei cookie.');
define('_PPTEXT2','Possiamo usare i dati per adattare e migliorare la vostra esperienza di cliente-utente su questo sito. Faremo in modo che i Dati in nostro possesso non vengano in nessun modo divulgati a terzi (i) provveda al contrario dentro Privacy Policy; (otteniamo il vostro consenso, come quando scegliete a OPT-in (ingresso) o OPT-out (uscita) alla compartecipazione dei dati;  (iii) un servizio fornito sul nostro luogo richiede l\'interazione con o è fornito dai terzi, ad esempio un fornitore di servizio di applicazione;  (iv) conforme ad applicazione legale di legge o di processo;  (v) troviamo che il vostro uso di questo luogo viola la nostra questa politica, i termini di servizio, l\'altra guida di riferimento di uso o come ritenuto ragionevolmente necessario da noi per proteggere i nostri diritti legali e/o proprietà;  (vi) o (vi) questo luogo è comprato dai terzi per cui quei terzi potranno usare i dati nello stesso modo come noi latta come disposta in questa politica.  Nel caso in cui scegliete di usare i collegamenti che ci sono nel nostro sito e visitate i siti vi raccomandiamo di leggere le politiche di privacy che compaiono su quei siti');
define('_PPTEXT3','Come molti siti, noi utilizziamo uso dei cookie per migliorare il servizio. Annunci pubblicitari possono apparire sul nostro sito e, in tal caso, può essere necessario settare i cookie di accesso sul Suo computer ed sarà soggetto alla politica di privacy di quelle parti che offrono l\'annuncio pubblicitario. Comunque, le società che servono la pubblicità non hanno accesso ai nostri cookie. Queste società di solito usano codici non-personalmente identificabili o anonimi per ottenere informazioni sulle Sue visite sul nostro sito.');
define('_PPTEXT4','Non permettiamo a persone che siano quattordicenni o più giovane diventare membri di questo sito. Per ulteriori informazioni, per favore contattate il nostro <a href=index.php?option=com_akolegal&Itemid='.$Itemid.'>webmaster</a>.');
define('_PPTEXT5','In ottemperanza della D.Lgs 196 del 30/06/03, codice in materia di protezione dei dati personali, (Art. 7) in ogni momento è i dati presenti nel nostro archivio e nella sua <a href="index.php?option=com_user&task=UserDetails">pagina personale</a> possono essere modificati o cancellati. Per la semplice cancellazione basta contattare il nostro <a href=index.php?option=com_akolegal&Itemid='.$Itemid.'> webmaster</a>. Per favore legga con attenzione le <a href="index.php?option=com_akolegal&Itemid='.$Itemid.'&func=terms">Condizioni d\'uso</a> per ulteriori informazioni.');
define('_PPTEXT6','Molte volte si renderà necessario aggiornare o modificare queste notizie. Noi Le notificheremo i cambi sostanziali attraverso annunci sul nostro sito e inviando una comunicazione all\'indirizzo di e-mail contenuto all\'interno del nostro database di utenti.');
define('_PPTEXT7','Queste regole sulla Privacy affermano i nostri standard per la manutenzione dei dati e noi faremo tutti gli sforzi per soddisfarli, però non le garantiamo sempre questi standard. Ci possono essere fattori fuori il nostro controllo che possono dare luogo alla rivelazione dei dati. Come conseguenza, non garantiamo la sicurezza relativa la manutenzione o la non rivelazione dei dati da noi raccolti.');
define('_PPTEXT8','Se avete qualunque domande circa questa politica o il nostro sito, si ritenga libero mettersi in contatto con il nostro <a href=index.php?option=com_akolegal&Itemid='.$Itemid.'>webmaster</a>.');
?>